package com.learning.learnandgrow.fragment

import android.app.Activity
import android.media.MediaPlayer
import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import com.learning.learnandgrow.R
import kotlinx.android.synthetic.main.fragment_letters.*
import kotlinx.android.synthetic.main.fragment_letters.view.*

class LettersFragment : Fragment() {

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        val view = inflater.inflate(R.layout.fragment_letters, container, false)

        var a = MediaPlayer.create(context as Activity, R.raw.a)
        var b = MediaPlayer.create(context as Activity, R.raw.b)
        var c = MediaPlayer.create(context as Activity, R.raw.c)
        var d = MediaPlayer.create(context as Activity, R.raw.d)
        var e = MediaPlayer.create(context as Activity, R.raw.e)
        var f = MediaPlayer.create(context as Activity, R.raw.f)
        var g = MediaPlayer.create(context as Activity, R.raw.g)
        var h = MediaPlayer.create(context as Activity, R.raw.h)
        var i = MediaPlayer.create(context as Activity, R.raw.i)
        var j = MediaPlayer.create(context as Activity, R.raw.j)
        var k = MediaPlayer.create(context as Activity, R.raw.k)
        var l = MediaPlayer.create(context as Activity, R.raw.l)
        var m = MediaPlayer.create(context as Activity, R.raw.m)
        var n = MediaPlayer.create(context as Activity, R.raw.n)
        var o = MediaPlayer.create(context as Activity, R.raw.o)
        var p = MediaPlayer.create(context as Activity, R.raw.p)
        var q = MediaPlayer.create(context as Activity, R.raw.q)
        var r = MediaPlayer.create(context as Activity, R.raw.r)
        var s = MediaPlayer.create(context as Activity, R.raw.s)
        var t = MediaPlayer.create(context as Activity, R.raw.t)
        var u = MediaPlayer.create(context as Activity, R.raw.u)
        var v = MediaPlayer.create(context as Activity, R.raw.v)
        var w = MediaPlayer.create(context as Activity, R.raw.w)
        var x = MediaPlayer.create(context as Activity, R.raw.x)
        var y = MediaPlayer.create(context as Activity, R.raw.y)
        var z = MediaPlayer.create(context as Activity, R.raw.z)

        view.btnA.setOnClickListener {

            // set gif
            btnA.setImageResource(R.drawable.a_cc)

            // unset gif
            btnB.setImageResource(R.drawable.b)
            btnC.setImageResource(R.drawable.c)
            btnD.setImageResource(R.drawable.d)
            btnE.setImageResource(R.drawable.e)
            btnF.setImageResource(R.drawable.f)
            btnG.setImageResource(R.drawable.g)
            btnH.setImageResource(R.drawable.h)


            // play
            a.start()

            // stop
            b.stop()
            c.stop()
            d.stop()
            e.stop()
            f.stop()
            g.stop()
            h.stop()
            i.stop()
            j.stop()
            k.stop()
            l.stop()
            m.stop()
            n.stop()
            o.stop()
            p.stop()
            q.stop()
            r.stop()
            s.stop()
            t.stop()
            u.stop()
            v.stop()
            w.stop()
            x.stop()
            y.stop()
            z.stop()

            // reset
            b = MediaPlayer.create(context as Activity, R.raw.b)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            y = MediaPlayer.create(context as Activity, R.raw.y)
            z = MediaPlayer.create(context as Activity, R.raw.z)
        }

        view.btnB.setOnClickListener {
            // set gif
            btnB.setImageResource(R.drawable.b_cc)

            // unset gif
            btnA.setImageResource(R.drawable.a)
            btnC.setImageResource(R.drawable.c)
            btnD.setImageResource(R.drawable.d)
            btnE.setImageResource(R.drawable.e)
            btnF.setImageResource(R.drawable.f)
            btnG.setImageResource(R.drawable.g)
            btnH.setImageResource(R.drawable.h)

            // play
            b.start()

            // stop
            a.stop()
            c.stop()
            d.stop()
            e.stop()
            f.stop()
            g.stop()
            h.stop()
            i.stop()
            j.stop()
            k.stop()
            l.stop()
            m.stop()
            n.stop()
            o.stop()
            p.stop()
            q.stop()
            r.stop()
            s.stop()
            t.stop()
            u.stop()
            v.stop()
            w.stop()
            x.stop()
            y.stop()
            z.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            y = MediaPlayer.create(context as Activity, R.raw.y)
            z = MediaPlayer.create(context as Activity, R.raw.z)
        }

        view.btnC.setOnClickListener {
            // set gif
            btnC.setImageResource(R.drawable.c_cc)

            // unset gif
            btnA.setImageResource(R.drawable.a)
            btnB.setImageResource(R.drawable.b)
            btnD.setImageResource(R.drawable.d)
            btnE.setImageResource(R.drawable.e)
            btnF.setImageResource(R.drawable.f)
            btnG.setImageResource(R.drawable.g)
            btnH.setImageResource(R.drawable.h)

            // play
            c.start()

            // stop
            a.stop()
            b.stop()
            d.stop()
            e.stop()
            f.stop()
            g.stop()
            h.stop()
            i.stop()
            j.stop()
            k.stop()
            l.stop()
            m.stop()
            n.stop()
            o.stop()
            p.stop()
            q.stop()
            r.stop()
            s.stop()
            t.stop()
            u.stop()
            v.stop()
            w.stop()
            x.stop()
            y.stop()
            z.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            b = MediaPlayer.create(context as Activity, R.raw.b)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            y = MediaPlayer.create(context as Activity, R.raw.y)
            z = MediaPlayer.create(context as Activity, R.raw.z)

        }

        view.btnD.setOnClickListener {
            // set gif
            btnD.setImageResource(R.drawable.d_cc)

            // unset gif
            btnA.setImageResource(R.drawable.a)
            btnB.setImageResource(R.drawable.b)
            btnC.setImageResource(R.drawable.c)
            btnE.setImageResource(R.drawable.e)
            btnF.setImageResource(R.drawable.f)
            btnG.setImageResource(R.drawable.g)
            btnH.setImageResource(R.drawable.h)

            // play
            d.start()

            // stop
            a.stop()
            b.stop()
            c.stop()
            e.stop()
            f.stop()
            g.stop()
            h.stop()
            i.stop()
            j.stop()
            k.stop()
            l.stop()
            m.stop()
            n.stop()
            o.stop()
            p.stop()
            q.stop()
            r.stop()
            s.stop()
            t.stop()
            u.stop()
            v.stop()
            w.stop()
            x.stop()
            y.stop()
            z.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            b = MediaPlayer.create(context as Activity, R.raw.b)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            y = MediaPlayer.create(context as Activity, R.raw.y)
            z = MediaPlayer.create(context as Activity, R.raw.z)

        }

        view.btnE.setOnClickListener {
            // set gif
            btnE.setImageResource(R.drawable.e_cc)

            // unset gif
            btnA.setImageResource(R.drawable.a)
            btnB.setImageResource(R.drawable.b)
            btnC.setImageResource(R.drawable.c)
            btnD.setImageResource(R.drawable.d)
            btnF.setImageResource(R.drawable.f)
            btnG.setImageResource(R.drawable.g)
            btnH.setImageResource(R.drawable.h)

            // play
            e.start()

            // stop
            a.stop()
            b.stop()
            c.stop()
            d.stop()
            f.stop()
            g.stop()
            h.stop()
            i.stop()
            j.stop()
            k.stop()
            l.stop()
            m.stop()
            n.stop()
            o.stop()
            p.stop()
            q.stop()
            r.stop()
            s.stop()
            t.stop()
            u.stop()
            v.stop()
            w.stop()
            x.stop()
            y.stop()
            z.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            b = MediaPlayer.create(context as Activity, R.raw.b)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            y = MediaPlayer.create(context as Activity, R.raw.y)
            z = MediaPlayer.create(context as Activity, R.raw.z)

        }

        view.btnF.setOnClickListener {
            // set gif
            btnF.setImageResource(R.drawable.f_cc)

            // unset gif
            btnA.setImageResource(R.drawable.a)
            btnB.setImageResource(R.drawable.b)
            btnC.setImageResource(R.drawable.c)
            btnD.setImageResource(R.drawable.d)
            btnE.setImageResource(R.drawable.e)
            btnG.setImageResource(R.drawable.g)
            btnH.setImageResource(R.drawable.h)

            // play
            f.start()

            // stop
            a.stop()
            b.stop()
            c.stop()
            d.stop()
            e.stop()
            g.stop()
            h.stop()
            i.stop()
            j.stop()
            k.stop()
            l.stop()
            m.stop()
            n.stop()
            o.stop()
            p.stop()
            q.stop()
            r.stop()
            s.stop()
            t.stop()
            u.stop()
            v.stop()
            w.stop()
            x.stop()
            y.stop()
            z.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            b = MediaPlayer.create(context as Activity, R.raw.b)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            y = MediaPlayer.create(context as Activity, R.raw.y)
            z = MediaPlayer.create(context as Activity, R.raw.z)

        }

        view.btnG.setOnClickListener {
            // set gif
            btnG.setImageResource(R.drawable.g_cc)

            // unset gif
            btnA.setImageResource(R.drawable.a)
            btnB.setImageResource(R.drawable.b)
            btnC.setImageResource(R.drawable.c)
            btnD.setImageResource(R.drawable.d)
            btnE.setImageResource(R.drawable.e)
            btnF.setImageResource(R.drawable.f)
            btnH.setImageResource(R.drawable.h)

            // play
            g.start()

            // stop
            a.stop()
            b.stop()
            c.stop()
            d.stop()
            e.stop()
            f.stop()
            h.stop()
            i.stop()
            j.stop()
            k.stop()
            l.stop()
            m.stop()
            n.stop()
            o.stop()
            p.stop()
            q.stop()
            r.stop()
            s.stop()
            t.stop()
            u.stop()
            v.stop()
            w.stop()
            x.stop()
            y.stop()
            z.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            b = MediaPlayer.create(context as Activity, R.raw.b)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            y = MediaPlayer.create(context as Activity, R.raw.y)
            z = MediaPlayer.create(context as Activity, R.raw.z)

        }

        view.btnH.setOnClickListener {
            // set gif
            btnH.setImageResource(R.drawable.h_cc)

            // unset gif
            btnA.setImageResource(R.drawable.a)
            btnB.setImageResource(R.drawable.b)
            btnC.setImageResource(R.drawable.c)
            btnD.setImageResource(R.drawable.d)
            btnE.setImageResource(R.drawable.e)
            btnF.setImageResource(R.drawable.f)
            btnG.setImageResource(R.drawable.g)

            // play
            h.start()

            // stop
            a.stop()
            b.stop()
            c.stop()
            d.stop()
            e.stop()
            f.stop()
            g.stop()
            i.stop()
            j.stop()
            k.stop()
            l.stop()
            m.stop()
            n.stop()
            o.stop()
            p.stop()
            q.stop()
            r.stop()
            s.stop()
            t.stop()
            u.stop()
            v.stop()
            w.stop()
            x.stop()
            y.stop()
            z.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            b = MediaPlayer.create(context as Activity, R.raw.b)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            y = MediaPlayer.create(context as Activity, R.raw.y)
            z = MediaPlayer.create(context as Activity, R.raw.z)

        }

        view.btnI.setOnClickListener {

            // play
            i.start()

            // stop
            a.stop()
            b.stop()
            c.stop()
            d.stop()
            e.stop()
            f.stop()
            g.stop()
            h.stop()
            j.stop()
            k.stop()
            l.stop()
            m.stop()
            n.stop()
            o.stop()
            p.stop()
            q.stop()
            r.stop()
            s.stop()
            t.stop()
            u.stop()
            v.stop()
            w.stop()
            x.stop()
            y.stop()
            z.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            b = MediaPlayer.create(context as Activity, R.raw.b)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            y = MediaPlayer.create(context as Activity, R.raw.y)
            z = MediaPlayer.create(context as Activity, R.raw.z)

        }

        view.btnJ.setOnClickListener {
            // play
            j.start()

            // stop
            a.stop()
            b.stop()
            c.stop()
            d.stop()
            e.stop()
            f.stop()
            g.stop()
            h.stop()
            i.stop()
            k.stop()
            l.stop()
            m.stop()
            n.stop()
            o.stop()
            p.stop()
            q.stop()
            r.stop()
            s.stop()
            t.stop()
            u.stop()
            v.stop()
            w.stop()
            x.stop()
            y.stop()
            z.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            b = MediaPlayer.create(context as Activity, R.raw.b)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            y = MediaPlayer.create(context as Activity, R.raw.y)
            z = MediaPlayer.create(context as Activity, R.raw.z)

        }

        view.btnK.setOnClickListener {

            // play
            k.start()

            // stop
            a.stop()
            b.stop()
            c.stop()
            d.stop()
            e.stop()
            f.stop()
            g.stop()
            h.stop()
            i.stop()
            j.stop()
            l.stop()
            m.stop()
            n.stop()
            o.stop()
            p.stop()
            q.stop()
            r.stop()
            s.stop()
            t.stop()
            u.stop()
            v.stop()
            w.stop()
            x.stop()
            y.stop()
            z.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            b = MediaPlayer.create(context as Activity, R.raw.b)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            y = MediaPlayer.create(context as Activity, R.raw.y)
            z = MediaPlayer.create(context as Activity, R.raw.z)

        }

        view.btnL.setOnClickListener {

            // play
            l.start()

            // stop
            a.stop()
            b.stop()
            c.stop()
            d.stop()
            e.stop()
            f.stop()
            g.stop()
            h.stop()
            i.stop()
            j.stop()
            k.stop()
            m.stop()
            n.stop()
            o.stop()
            p.stop()
            q.stop()
            r.stop()
            s.stop()
            t.stop()
            u.stop()
            v.stop()
            w.stop()
            x.stop()
            y.stop()
            z.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            b = MediaPlayer.create(context as Activity, R.raw.b)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            y = MediaPlayer.create(context as Activity, R.raw.y)
            z = MediaPlayer.create(context as Activity, R.raw.z)

        }

        view.btnM.setOnClickListener {

            // play
            m.start()

            // stop
            a.stop()
            b.stop()
            c.stop()
            d.stop()
            e.stop()
            f.stop()
            g.stop()
            h.stop()
            i.stop()
            j.stop()
            k.stop()
            l.stop()
            n.stop()
            o.stop()
            p.stop()
            q.stop()
            r.stop()
            s.stop()
            t.stop()
            u.stop()
            v.stop()
            w.stop()
            x.stop()
            y.stop()
            z.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            b = MediaPlayer.create(context as Activity, R.raw.b)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            y = MediaPlayer.create(context as Activity, R.raw.y)
            z = MediaPlayer.create(context as Activity, R.raw.z)

        }

        view.btnN.setOnClickListener {

            // play
            n.start()

            // stop
            a.stop()
            b.stop()
            c.stop()
            d.stop()
            e.stop()
            f.stop()
            g.stop()
            h.stop()
            i.stop()
            j.stop()
            k.stop()
            l.stop()
            m.stop()
            o.stop()
            p.stop()
            q.stop()
            r.stop()
            s.stop()
            t.stop()
            u.stop()
            v.stop()
            w.stop()
            x.stop()
            y.stop()
            z.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            b = MediaPlayer.create(context as Activity, R.raw.b)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            y = MediaPlayer.create(context as Activity, R.raw.y)
            z = MediaPlayer.create(context as Activity, R.raw.z)

        }

        view.btnO.setOnClickListener {

            // play
            o.start()

            // stop
            a.stop()
            b.stop()
            c.stop()
            d.stop()
            e.stop()
            f.stop()
            g.stop()
            h.stop()
            i.stop()
            j.stop()
            k.stop()
            l.stop()
            m.stop()
            n.stop()
            p.stop()
            q.stop()
            r.stop()
            s.stop()
            t.stop()
            u.stop()
            v.stop()
            w.stop()
            x.stop()
            y.stop()
            z.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            b = MediaPlayer.create(context as Activity, R.raw.b)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            y = MediaPlayer.create(context as Activity, R.raw.y)
            z = MediaPlayer.create(context as Activity, R.raw.z)

        }

        view.btnP.setOnClickListener {

            // play
            p.start()

            // stop
            a.stop()
            b.stop()
            c.stop()
            d.stop()
            e.stop()
            f.stop()
            g.stop()
            h.stop()
            i.stop()
            j.stop()
            k.stop()
            l.stop()
            m.stop()
            n.stop()
            o.stop()
            q.stop()
            r.stop()
            s.stop()
            t.stop()
            u.stop()
            v.stop()
            w.stop()
            x.stop()
            y.stop()
            z.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            b = MediaPlayer.create(context as Activity, R.raw.b)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            y = MediaPlayer.create(context as Activity, R.raw.y)
            z = MediaPlayer.create(context as Activity, R.raw.z)
        }

        view.btnQ.setOnClickListener {

            // play
            q.start()

            // stop
            a.stop()
            b.stop()
            c.stop()
            d.stop()
            e.stop()
            f.stop()
            g.stop()
            h.stop()
            i.stop()
            j.stop()
            k.stop()
            l.stop()
            m.stop()
            n.stop()
            o.stop()
            p.stop()
            r.stop()
            s.stop()
            t.stop()
            u.stop()
            v.stop()
            w.stop()
            x.stop()
            y.stop()
            z.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            b = MediaPlayer.create(context as Activity, R.raw.b)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            y = MediaPlayer.create(context as Activity, R.raw.y)
            z = MediaPlayer.create(context as Activity, R.raw.z)

        }

        view.btnR.setOnClickListener {

            // play
            r.start()

            // stop
            a.stop()
            b.stop()
            c.stop()
            d.stop()
            e.stop()
            f.stop()
            g.stop()
            h.stop()
            i.stop()
            j.stop()
            k.stop()
            l.stop()
            m.stop()
            n.stop()
            o.stop()
            p.stop()
            q.stop()
            s.stop()
            t.stop()
            u.stop()
            v.stop()
            w.stop()
            x.stop()
            y.stop()
            z.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            b = MediaPlayer.create(context as Activity, R.raw.b)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            y = MediaPlayer.create(context as Activity, R.raw.y)
            z = MediaPlayer.create(context as Activity, R.raw.z)

        }

        view.btnS.setOnClickListener {

            // play
            s.start()

            // stop
            a.stop()
            b.stop()
            c.stop()
            d.stop()
            e.stop()
            f.stop()
            g.stop()
            h.stop()
            i.stop()
            j.stop()
            k.stop()
            l.stop()
            m.stop()
            n.stop()
            o.stop()
            p.stop()
            q.stop()
            r.stop()
            t.stop()
            u.stop()
            v.stop()
            w.stop()
            x.stop()
            y.stop()
            z.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            b = MediaPlayer.create(context as Activity, R.raw.b)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            y = MediaPlayer.create(context as Activity, R.raw.y)
            z = MediaPlayer.create(context as Activity, R.raw.z)

        }

        view.btnT.setOnClickListener {

            // play
            t.start()

            // stop
            a.stop()
            b.stop()
            c.stop()
            d.stop()
            e.stop()
            f.stop()
            g.stop()
            h.stop()
            i.stop()
            j.stop()
            k.stop()
            l.stop()
            m.stop()
            n.stop()
            o.stop()
            p.stop()
            q.stop()
            r.stop()
            s.stop()
            u.stop()
            v.stop()
            w.stop()
            x.stop()
            y.stop()
            z.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            b = MediaPlayer.create(context as Activity, R.raw.b)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            y = MediaPlayer.create(context as Activity, R.raw.y)
            z = MediaPlayer.create(context as Activity, R.raw.z)

        }

        view.btnU.setOnClickListener {
            // play
            u.start()

            // stop
            a.stop()
            b.stop()
            c.stop()
            d.stop()
            e.stop()
            f.stop()
            g.stop()
            h.stop()
            i.stop()
            j.stop()
            k.stop()
            l.stop()
            m.stop()
            n.stop()
            o.stop()
            p.stop()
            q.stop()
            r.stop()
            s.stop()
            t.stop()
            v.stop()
            w.stop()
            x.stop()
            y.stop()
            z.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            b = MediaPlayer.create(context as Activity, R.raw.b)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            y = MediaPlayer.create(context as Activity, R.raw.y)
            z = MediaPlayer.create(context as Activity, R.raw.z)

        }

        view.btnV.setOnClickListener {

            // play
            v.start()

            // stop
            a.stop()
            b.stop()
            c.stop()
            d.stop()
            e.stop()
            f.stop()
            g.stop()
            h.stop()
            i.stop()
            j.stop()
            k.stop()
            l.stop()
            m.stop()
            n.stop()
            o.stop()
            p.stop()
            q.stop()
            r.stop()
            s.stop()
            t.stop()
            u.stop()
            w.stop()
            x.stop()
            y.stop()
            z.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            b = MediaPlayer.create(context as Activity, R.raw.b)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            y = MediaPlayer.create(context as Activity, R.raw.y)
            z = MediaPlayer.create(context as Activity, R.raw.z)

        }

        view.btnW.setOnClickListener {

            // play
            w.start()

            // stop
            a.stop()
            b.stop()
            c.stop()
            d.stop()
            e.stop()
            f.stop()
            g.stop()
            h.stop()
            i.stop()
            j.stop()
            k.stop()
            l.stop()
            m.stop()
            n.stop()
            o.stop()
            p.stop()
            q.stop()
            r.stop()
            s.stop()
            t.stop()
            u.stop()
            v.stop()
            x.stop()
            y.stop()
            z.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            b = MediaPlayer.create(context as Activity, R.raw.b)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            y = MediaPlayer.create(context as Activity, R.raw.y)
            z = MediaPlayer.create(context as Activity, R.raw.z)

        }

        view.btnX.setOnClickListener {

            // play
            x.start()

            // stop
            a.stop()
            b.stop()
            c.stop()
            d.stop()
            e.stop()
            f.stop()
            g.stop()
            h.stop()
            i.stop()
            j.stop()
            k.stop()
            l.stop()
            m.stop()
            n.stop()
            o.stop()
            p.stop()
            q.stop()
            r.stop()
            s.stop()
            t.stop()
            u.stop()
            v.stop()
            w.stop()
            y.stop()
            z.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            b = MediaPlayer.create(context as Activity, R.raw.b)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            y = MediaPlayer.create(context as Activity, R.raw.y)
            z = MediaPlayer.create(context as Activity, R.raw.z)

        }

        view.btnY.setOnClickListener {

            // play
            y.start()

            // stop
            a.stop()
            b.stop()
            c.stop()
            d.stop()
            e.stop()
            f.stop()
            g.stop()
            h.stop()
            i.stop()
            j.stop()
            k.stop()
            l.stop()
            m.stop()
            n.stop()
            o.stop()
            p.stop()
            q.stop()
            r.stop()
            s.stop()
            t.stop()
            u.stop()
            v.stop()
            w.stop()
            x.stop()
            z.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            b = MediaPlayer.create(context as Activity, R.raw.b)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            z = MediaPlayer.create(context as Activity, R.raw.z)
        }

        view.btnZ.setOnClickListener {

            // play
            z.start()

            // stop
            a.stop()
            b.stop()
            c.stop()
            d.stop()
            e.stop()
            f.stop()
            g.stop()
            h.stop()
            i.stop()
            j.stop()
            k.stop()
            l.stop()
            m.stop()
            n.stop()
            o.stop()
            p.stop()
            q.stop()
            r.stop()
            s.stop()
            t.stop()
            u.stop()
            v.stop()
            w.stop()
            x.stop()
            y.stop()

            // reset
            a = MediaPlayer.create(context as Activity, R.raw.a)
            b = MediaPlayer.create(context as Activity, R.raw.b)
            c = MediaPlayer.create(context as Activity, R.raw.c)
            d = MediaPlayer.create(context as Activity, R.raw.d)
            e = MediaPlayer.create(context as Activity, R.raw.e)
            f = MediaPlayer.create(context as Activity, R.raw.f)
            g = MediaPlayer.create(context as Activity, R.raw.g)
            h = MediaPlayer.create(context as Activity, R.raw.h)
            i = MediaPlayer.create(context as Activity, R.raw.i)
            j = MediaPlayer.create(context as Activity, R.raw.j)
            k = MediaPlayer.create(context as Activity, R.raw.k)
            l = MediaPlayer.create(context as Activity, R.raw.l)
            m = MediaPlayer.create(context as Activity, R.raw.m)
            n = MediaPlayer.create(context as Activity, R.raw.n)
            o = MediaPlayer.create(context as Activity, R.raw.o)
            p = MediaPlayer.create(context as Activity, R.raw.p)
            q = MediaPlayer.create(context as Activity, R.raw.q)
            r = MediaPlayer.create(context as Activity, R.raw.r)
            s = MediaPlayer.create(context as Activity, R.raw.s)
            t = MediaPlayer.create(context as Activity, R.raw.t)
            u = MediaPlayer.create(context as Activity, R.raw.u)
            v = MediaPlayer.create(context as Activity, R.raw.v)
            w = MediaPlayer.create(context as Activity, R.raw.w)
            x = MediaPlayer.create(context as Activity, R.raw.x)
            y = MediaPlayer.create(context as Activity, R.raw.y)
        }

        return view
    }
}